### ISSUE TITLE
Creative Request Form: Character limit for Project Name Field

### ISSUE THREAD

**Issue by RescueAgency** [RescueAgencyInternal/Project-Request-App#1]
Please add a 60 character limit on the Project Name field on the Creative request form.

![image](https://user-images.githubusercontent.com/35040134/50710079-d4fe2700-101e-11e9-9331-10a3cf3eb842.png)

**Comment by RescueAgency** [comment]
@RescueChris Can I get an ETA on this? Thanks!

**Comment by RescueAgencyMaster** [comment]
@RescueAgency  I'll get this updated by EoD today

**Comment by RescueAgencyMaster** [comment]
Completed, tested, & deployed
