### ISSUE TITLE
Staging Request Form: Make Project Type Multi-select

### ISSUE THREAD

**Issue by RescueAgency** [RescueAgencyInternal/Project-Request-App#2]
- [ ] Make Staging Requests "Select a Type of Staging Request" dropdown multi-select
- [ ] Make the file name include all types of projects selected
- [ ] Make sure the automated emails are including the long file name
- [ ] Update search filter on Saved Drafts and Submitted requests capable of finding staging requests that have multiple projects selected

![image](https://user-images.githubusercontent.com/35040134/50710370-ab91cb00-101f-11e9-909b-fbaca7fbd181.png)

**Comment by RescueAgency** [comment]
@RescueChris Can I get an ETA on this? This item is marked as High Priority.

Thanks!

**Comment by RescueAgencyMaster** [comment]
@RescueAgency This will require a change in how the database handles this particular field so I would expect it to be done by EoW with roll out over the weekend so I can test it in the production environment without interruption.

**Comment by RescueAgency** [comment]
@RescueChris Where are we at on this issue? Thanks!

**Comment by RescueAgencyMaster** [comment]
I've just about fixed the issue.  I'm going to take a bit of a break and wrap this up for deployment tomorrow or worst case scenario over the weekend.  The fix ended up being far more complicated than originally anticipated but now that I've got it figured out we've got a great solution for migrating this type of data.
