### ISSUE TITLE
Hiding of Drafts and Submitted Requests When Deleting

### ISSUE THREAD

**Issue by RescueAgency** [RescueAgencyInternal/Project-Request-App#5]
- [ ] Change functionality so when a user deletes a draft or a submitted request they are not actually deleted. Instead, they are hidden until an admin level user searches for them
- [ ] Add in functionality to restore deleted items, which will make them visible again to all users

**Comment by RescueAgency** [comment]
@RescueChris Can I get an ETA on this? Thanks!

**Comment by RescueAgencyMaster** [comment]
@RescueAgency I'll get this updated by EoW with release on Monday, this should be a fairly simple add but want to make sure I test it in the production environment over the weekend

**Comment by RescueAgencyMaster** [comment]
Completed, tested, & deployed.  When deleting a new field is flagged called **Deleted**.  This field determines whether it is visible for end users as only Creative Ops team members or admins can undo a deletion using the restore button seen in the screenshot below.

![screen shot 2019-01-24 at 6 19 34 am](https://user-images.githubusercontent.com/46385196/51696035-5bbc7900-1fb9-11e9-9a1c-3517bc03661e.png)
