### ISSUE TITLE
Staging Requests - Remove Start and due Date Fields

### ISSUE THREAD

**Issue by RescueAgency** [RescueAgencyInternal/Project-Request-App#6]
Please remove start and due date fields from STAGING requests (it will remain on the creative requests form). 

![image](https://user-images.githubusercontent.com/35040134/51149251-245e0780-1816-11e9-9111-322cb304fd35.png)

**Comment by RescueAgencyMaster** [comment]
@RescueAgency this is an easy fix so I'll roll this into Monday's update.

**Comment by RescueAgencyMaster** [comment]
Completed, tested, & deployed
