### ISSUE TITLE
Bug: How-to Videos

### ISSUE THREAD

**Issue by RescueAgency** [RescueAgencyInternal/Project-Request-App#7]
- [ ] Fix how-to videos so they have sound

Videos in Google Drive do not play with sound in preview mode when viewed on folder:
https://drive.google.com/drive/folders/1bnMSB9o6K2zI6FmXeAnk7iNbDlP32a4S

This is resulting on the How-to Videos in the side panel on the Project Request App to not have sound as well:
![image](https://user-images.githubusercontent.com/35040134/52447298-39604a80-2ae5-11e9-875c-7ef621a25a3f.png)

**Comment by RescueAgency** [comment]
Hi there! Can I get an update on this?

**Comment by RescueAgencyMaster** [comment]
Update completed, turns out Google doesn't like audio in the .mp4 formatted previews.  I converted it to .mov and the videos worked properly.  Will push to live tonight with the rest of the changes.  Will mark as completed when pushed live and tested there.
