### ISSUE TITLE
Teamwork Staged Email Text Changes

### ISSUE THREAD

**Issue by RescueAgency** [RescueAgencyInternal/Project-Request-App#8]
Please change the following automated email that is sent when a TW task is connected from:

Hello, 
your request for 509-Syke-Syke VA submitted on 03/13/19 has been staged in Teamwork, you may view it here:

If you need to make changes to your request, please send an email to both: jason@rescueagency.com and jzawisa@rescueagency.com

Thank you!

TO:
Hello, 
your request for 509-Syke-Syke VA submitted on 03/13/19 has been staged in Teamwork, you may view it here: 
**INSERT ACTUAL URL to TW TASK, IT WAS MISSING**

**If you have updated information for your CR comment on the TW task the CR is attached to and tag the impacted parties.** 

Thank you!

(no need to make the text bold, just emphasizing so you know what changed.

**Comment by RescueAgencyMaster** [comment]
Updated verbiage and added a 3 second delay from when the Creative Ops member submits the Teamwork link to when the email is sent out in case there is any delay between the data being sent to the database and when the email function starts.  Will push live tonight with remaining changes and mark as completed after testing on live.
