### ISSUE TITLE
File Selection from Google Drive

### ISSUE THREAD

**Issue by RescueAgency** [RescueAgencyInternal/Project-Request-App#9]
Hi Chris!

Here are the deets for that new feature:

- Add a section to Link File from G-Drive on both the Creative Request and Staging Request forms
- Make it populate a pop-up to select files, should be able to access both the users My Drive and Team Drives
- Should be able to select just Folders as well as actual files
- Links should be displayed as a list
- Links should be able to be deleted from request while the request is being created/edited

![image](https://user-images.githubusercontent.com/35040134/55976607-a60cd800-5c41-11e9-9ff2-006275b0640c.png)
![image](https://user-images.githubusercontent.com/35040134/55976645-c046b600-5c41-11e9-9522-11f0087030c0.png)

**Comment by RescueAgencyMaster** [comment]
Deployed last week.  Thus far have not gotten any feedback from end users regarding issues and I have seen it being used in some of the newer requests coming through.
